<template>
  <div class="SubWebPage">
    <simple-page-list :setting="setting"></simple-page-list>
  </div>
</template>

<script>
import Vue from "vue";
import SimplePageList from "@/components/SimplePageList.vue";
export default Vue.extend({
  components: { SimplePageList },
  methods: {},
  data() {
    return {
      setting: {
        title: "用户列表",
        action: "/api/user",
        searchFormItem: [
          { type: "text", prop: "Keywords", label: "关键字", span: 12 },
          {
            type: "daterange",
            prop: "CreatedTime",
            label: "创建时间",
            span: 12,
          },
          {
            type: "select",
            prop: "SchoolId",
            label: "学校",
            action: "/api/school/school-dropdown-box",
            options: [],
            loading: false,
            span: 12,
          },
          {
            type: "select",
            prop: "RoleId",
            label: "角色",
            action: "/api/user/roles",
            options: [],
            loading: false,
            span: 12,
          },
        ],
        titleBtns: [
          {
            type: "drawer",
            theme: "primary",
            icon: "el-icon-plus",
            label: "添加",
            drawer: "add",
            power: "SystemMgr_UserMgr_Post",
          },
        ],
        rowBtns: [
          {
            type: "drawer",
            theme: "default",
            icon: "el-icon-info",
            label: "查看",
            drawer: "detail",
            power: "SystemMgr_UserMgr_Get",
          },
          {
            type: "drawer",
            theme: "warning",
            icon: "el-icon-edit",
            label: "编辑",
            drawer: "edit",
            power: "SystemMgr_UserMgr_Edit",
          },
        ],
        batchBtns: [
          {
            type: "drawer",
            theme: "warning",
            icon: "el-icon-edit",
            label: "设置密码",
            drawer: "repassword",
            power: "SystemMgr_UserMgr_RePassword",
          },
          {
            type: "api",
            theme: "success",
            icon: "el-icon-edit",
            label: "启用",
            method: "post",
            action: "/api/user/enable",
            params: { Enable: true },
            power: "SystemMgr_UserMgr_Enable",
          },
          {
            type: "api",
            theme: "danger",
            icon: "el-icon-edit",
            label: "禁用",
            method: "post",
            action: "/api/user/enable",
            params: { Enable: false },
            power: "SystemMgr_UserMgr_Enable",
          },
        ],
        columns: [
          { prop: "SchoolName", label: "学校" },
          { prop: "Code", label: "工号", width: "90px" },
          { prop: "Account", label: "账号", width: "110px" },
          { prop: "Name", label: "姓名", width: "120px" },
          {
            prop: "Enable",
            label: "启用",
            pipe: "bool",
            pipeArgs: ["是", "否"],
            width: "50px",
          },
          {
            prop: "UserRoles_RoleName",
            label: "角色",
            nesting: true,
            width: "100px",
          },
          {
            prop: "CreatedTime",
            label: "注册时间",
            pipe: "date",
            pipeArgs: ["YYYY/MM/DD hh:mm"],
            width: "140px",
          },
        ],
        check: true,
        index: true,
        drawers: [
          {
            name: "repassword",
            type: "form",
            action: "/api/user/re-password",
            show: false,
            ids: [],
            items: [
              {
                prop: "Password",
                label: "密码",
                type: "text",
                required: true,
                pattern: /^[0-9a-zA-Z\x21-\x7e]{5,24}$/,
                patternMsg: "密码只能由字母、数字、标点符号组成的5~24位字符！",
                span: 24,
              },
            ],
          },
          {
            name: "detail",
            type: "detail",
            action: "/api/user",
            show: false,
            id: undefined,
            items: [
              {
                prop: "Account",
                label: "账号",
                type: "text",
                span: 24,
              },
              {
                prop: "Name",
                label: "姓名",
                type: "text",
                span: 24,
              },
              {
                prop: "Code",
                label: "工号",
                type: "text",
                span: 24,
              },
              {
                prop: "Enable",
                label: "启用",
                type: "text",
                span: 24,
                pipe: "bool",
                pipeArgs: ["是", "否"],
              },
              {
                prop: "SchoolName",
                label: "学校",
                type: "text",
                span: 24,
              },
              {
                prop: "UserRoles_RoleName",
                nesting: true,
                label: "角色",
                type: "text",
                span: 24,
              },
              {
                prop: "CreatedTime",
                label: "注册时间",
                type: "text",
                pipe: "date",
                pipeArgs: ["YYYY/MM/DD hh:mm"],
                span: 24,
              },
            ],
          },
          {
            name: "add",
            type: "form",
            action: "/api/user",
            show: false,
            id: undefined,
            items: [
              {
                prop: "Code",
                label: "工号",
                type: "text",
                max: 256,
                span: 24,
              },
              {
                prop: "Name",
                label: "姓名",
                type: "text",
                required: true,
                max: 256,
                span: 24,
              },
              {
                prop: "Account",
                label: "账号",
                type: "text",
                required: true,
                pattern: /^[0-9a-zA-Z]{5,24}$/,
                patternMsg: "账号只能由字母、数字组成的5~24位字符！",
                span: 24,
              },
              {
                prop: "Password",
                label: "密码",
                type: "password",
                required: true,
                pattern: /^[0-9a-zA-Z\x21-\x7e]{5,24}$/,
                patternMsg: "密码只能由字母、数字、标点符号组成的5~24位字符！",
                span: 24,
              },
              {
                prop: "RePassword",
                label: "确认密码",
                type: "password",
                required: true,
                pattern: /^[0-9a-zA-Z\x21-\x7e]{5,24}$/,
                patternMsg: "密码只能由字母、数字、标点符号组成的5~24位字符！",
                someTo: "Password",
                someToMsg: "两次输入密码不一致",
                span: 24,
              },
              {
                prop: "Enable",
                label: "启用",
                type: "check",
                default: true,
                span: 24,
              },
              {
                prop: "SchoolName",
                label: "学校",
                type: "select",
                allowcreate: true,
                span: 24,
                action: "/api/school/school-allow-create-dropdown-box",
                options: [],
                loading: false,
              },
              {
                prop: "UserRoles_RoleId",
                nesting: true,
                label: "角色",
                type: "select",
                span: 24,
                action: "/api/user/roles",
                options: [],
                multiple: true,
                loading: false,
              },
            ],
          },
          {
            name: "edit",
            type: "form",
            action: "/api/user",
            show: false,
            id: undefined,
            items: [
              {
                prop: "Code",
                label: "工号",
                type: "text",
                max: 256,
                span: 24,
              },
              {
                prop: "Name",
                label: "姓名",
                type: "text",
                required: true,
                max: 256,
                span: 24,
              },
              {
                prop: "Account",
                label: "账号",
                type: "text",
                required: true,
                pattern: /^[0-9a-zA-Z]{5,24}$/,
                patternMsg: "账号只能由字母、数字组成的5~24位字符！",
                span: 24,
              },
              {
                prop: "Enable",
                label: "启用",
                type: "check",
                default: true,
                span: 24,
              },
              {
                prop: "SchoolName",
                label: "学校",
                type: "select",
                allowcreate: true,
                span: 24,
                action: "/api/school/school-allow-create-dropdown-box",
                options: [],
                loading: false,
              },
              {
                prop: "UserRoles_RoleId",
                nesting: true,
                label: "角色",
                type: "select",
                span: 24,
                action: "/api/user/roles",
                options: [],
                multiple: true,
                loading: false,
              },
            ],
          },
        ],
      },
    };
  },
});
</script>

<style lang="sass" scoped>
</style>